name: Typescript SDK PR Workflow

on: workflow_dispatch

jobs:
  build_and_test_sdk:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        operating-system: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --frozen-lockfile=true

      - name: Build
        working-directory: ./typescript_sdk/reality_capture
        run: npm build

      # - name: Build doc

      # - name: Run unit tests
      #   env:
      #     IMJS_UNIT_TESTS_PROJECT_ID: ${{ secrets.UNIT_TESTS_PROJECT_ID }}
      #     IMJS_UNIT_TESTS_CLIENT_ID: ${{ secrets.UNIT_TESTS_CLIENT_ID }}
      #     IMJS_UNIT_TESTS_SECRET: ${{ secrets.UNIT_TESTS_SECRET }}
      #   run: pnpm coverage

      - name: Publish packages as tgz
        if: ${{ matrix.os == 'windows-latest' && startsWith(matrix.node-version, '22')}}
        working-directory: ./typescript_sdk/reality_capture
        run: npm pack --pack-destination ./lib
