name: Publish Python SDK

on: workflow_dispatch

jobs:
  build_and_publish_sdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Create virtual env
      run: |
        python -m venv venv 

    - name: Build wheel
      working-directory: ./python_sdk
      run: |
        source ../venv/bin/activate
        python -m pip install build
        python -m build
        deactivate

    - name: Build documentation
      working-directory: ./python_sdk
      run: |
        source ../venv/bin/activate
        pip install .[dev]
        cd dist
        python -m pip install *.whl
        cd ../docs
        make.bat html
        deactivate

    - name: Find Wheel File
      id: find_wheel
      run: |
        WHEEL=$(ls dist/*.whl | head -n 1)
        echo "::set-output name=wheel::$WHEEL"

    - name: Create Pre-Release
      uses: actions/create-release@v1
      id: create_pre_release
      with:
        tag_name: 2.0.0-alpha.1
        release_name: "Version 2.0.0-alpha.1"
        draft: false
        prerelease: true

    - name: Upload wheel
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_pre_release.outputs.upload_url }}
        asset_path: ${{ steps.find_wheel.outputs.wheel }}
        asset_name: ${{ steps.find_wheel.outputs.wheel }}
        asset_content_type: application/octet-stream

    
    

