name: (PyPreRelease) Publish Python SDK Pre-Release

on: workflow_dispatch

# Creates a pre-release in Github repo. Does not publish package to Pypi
# Delegates all logic to python-publish.yml
jobs:
  publish:
    uses: ./.github/workflows/python-publish.yml
    with:
      prerelease: true
