name: (RCPackPublish) Pack and publish reality-capture GitHub release

on:
  workflow_call:
    inputs:
      prerelease:
        required: true
        type: boolean

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Publish packages in npm
        working-directory: ./typescript/packages/reality-capture
        shell: pwsh
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
          if ("${{ inputs.prerelease }}" -eq "true") {
            pnpm publish-packages-dev -y --branch origin/${{ github.ref_name }} --message "Version bump [skip actions]"
          }
          else {
            pnpm publish-packages -y --branch origin/${{ github.ref_name }} --message "Version bump [skip actions]"
          }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
