name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: test
        run: | 
          echo registry=https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/ > .npmrc
          echo @bentley:registry=https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/ >> .npmrc
          echo @itwin:registry=https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/ >> .npmrc
          echo always-auth=true >> .npmrc
          vsts-npm-auth -config ./typescript/.npmrc -f
      - name: Install
        working-directory: ./typescript
        run: npm install
      - name: Typescript compiler
        working-directory: ./typescript
        run: npx tsc
      - name: EsLint
        working-directory: ./typescript
        run: npm run lint