name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Setup Azure Artifacts Authentication
        run: |
          npm config set @bentley:registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
          npm config set @itwin:registry https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:username=VssSessionToken
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:_password=${{ secrets.NPM_TOKEN }}
          npm config set //pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/:email=not-used@example.com
      - name: Install WebApp
        working-directory: ./typescript/WebApp
        run: npm install --no-save
      - name: Install SDK
        working-directory: ./typescript/SDK
        run: npm install --no-save
      - name: Typescript compiler (WebApp)
        working-directory: ./typescript/Webapp
        run: npx tsc
      - name: Typescript compiler (SDK)
        working-directory: ./typescript/SDK
        run: npx tsc
      - name: EsLint
        working-directory: ./typescript/WebApp
        run: npm run lint