name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm config set registry=https://pkgs.dev.azure.com/bentleycs/_packaging/Packages/npm/registry/
      - run: npm config set always-auth=true
      - run: cd /d %UserProfile%
      - run: npm install -g vsts-npm-auth --registry https://registry.npmjs.com --always-auth false
      - run: vsts-npm-auth -config .npmrc -f
      - name: Install dependencies
        working-directory: typescript
        run: npm install
      - name: Typescript compiler
        run: npx tsc
      - name: EsLint
        working-directory: ./typescript
        run: npm run lint